import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("ecommerce_customer_behavior_5000.csv")
df.columns=df.columns.str.strip()
df["order_date"]=pd.to_datetime(df["order_date"])
print("\nmissing values:\n")
print(df.isnull().sum())
print("\ndataset info:\n")
print(df.info())
print("\nfirst 5 rows:\n")
print(df.head())
total_orders=df["order_id"].count()
print("\ntotal orders:\n",round(total_orders,2))
avg_rating=df["customer_rating"].mean()
print("\naverage rating:",round(avg_rating,2))
avg_delivery=df["delivery_time_days"].mean()
print("\naverage delivery time:",round(avg_delivery,2))
category_sales=df.groupby("product_category")["order_value_usd"].sum().sort_values(ascending=False)
print("\nsales by product category:\n",category_sales)
plt.figure(figsize=(8,5))
category_sales.plot(kind="bar",color="blue")
plt.title("sales by product category")
plt.xlabel("product category")
plt.ylabel("sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
payment_count=df["payment_method"].value_counts()
print("\npayment method usage:\n",payment_count)
plt.figure(figsize=(6,6))
payment_count.plot(kind="pie",autopct="%1.1f%%")
plt.title("payment method")
plt.ylabel("")
plt.show()
def rating_group(rating):
    if rating>=4:
        return "high satisfaction"
    elif rating>=2.5:
        return "medium satisfaction"
    else:
        return "low satisfaction"
df["satisfaction_level"]=df["customer_rating"].apply(rating_group)
satisfaction_count=df["satisfaction_level"].value_counts()
print("\n customer satisfaction levels:\n",satisfaction_count)
plt.figure(figsize=(6,4))
satisfaction_count.plot(kind="bar",color="red")
plt.title("customer satisfaction")
plt.xlabel("customer satisfaction")
plt.ylabel("number of customers")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
delivery_rating=df.groupby("delivery_time_days")["customer_rating"].mean()
plt.figure(figsize=(8,5))
delivery_rating.plot(marker="o")
plt.title("delivery time vs customer rating")
plt.xlabel("delivery time days")
plt.ylabel("average rating")
plt.grid(True)
plt.tight_layout()
plt.show()
return_analysis=df.groupby("returned")["customer_rating"].mean()
print("\nreturn analysis:\n",return_analysis)
plt.figure(figsize=(5,4))
return_analysis.plot(kind="bar",color="blue")
plt.title("return vs customer rating")
plt.xlabel("returned")
plt.ylabel("average rating")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()
loyal_customers=df[(df["customer_rating"]>=4)&(df["order_value_usd"]>df["order_value_usd"].mean())]
print("\n number of loyal customers:\n",loyal_customers.shape[0])
df["month"]=df["order_date"].dt.to_period("M")
monthly_sales=df.groupby("month")["order_value_usd"].sum()
plt.figure(figsize=(10,5))
monthly_sales.plot(marker="o")
plt.title("monthly sales")
plt.xlabel("month")
plt.ylabel("sales")
plt.grid(True)
plt.tight_layout()
plt.show()
