import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("netflix_titles.csv")
print("first 5 rows:\n")
print(df.head())
print("\ndataset shape:\n")
print(df.shape)
print("columns:\n")
print(df.columns)
print("missing values:\n")
print(df.isnull().sum())
df=df.drop_duplicates()
df["country"]=df["country"].fillna("Unknown")
df["director"]=df["director"].fillna("Not Available")
df["cast"]=df["cast"].fillna("Not Available")
df["rating"]=df["rating"].fillna("Unknown")
df["duration"]=df["duration"].fillna("Unknown")
df["date_added"]=pd.to_datetime(df["date_added"],errors="coerce")
df["year_added"]=df["date_added"].dt.year
print("\ncleaning dataset info:\n")
print(df.info())
content_type=df["type"].value_counts()
print(content_type)
plt.figure(figsize=(6,5))
content_type.plot(kind="bar",color="green")
plt.title("movies vs TV shows")
plt.xlabel("type")
plt.ylabel("count")
plt.xticks(rotation=0)
plt.show()
content_by_year=df["year_added"].value_counts().sort_index()
print(content_by_year)
plt.figure(figsize=(12,6))
content_by_year.plot(kind="line",marker="o",color="black")
plt.title("Netflix content added over years")
plt.xlabel("year")
plt.ylabel("number of shows")
plt.grid(True)
plt.show()
country_data=df["country"].value_counts().head(10)
print(country_data)
plt.figure(figsize=(10,6))
country_data.plot(kind="bar",color="grey")
plt.title("Top 10 countries with most netflix content")
plt.xlabel("country")
plt.ylabel("content count")
plt.xticks(rotation=0)
plt.show()
rating_data=df["rating"].value_counts().head(10)
print(rating_data)
plt.figure(figsize=(10,6))
rating_data.plot(kind="bar",color="orange")
plt.title("Netflix content rating")
plt.xlabel("rating")
plt.ylabel("count")
plt.xticks(rotation=0)
plt.show()
genres=df["listed_in"].str.split(",",expand=True).stack()
genre_count=genres.value_counts().head(10)
print("\n top genres:\n")
print(genre_count)
plt.figure(figsize=(12,6))
genre_count.plot(kind="bar",color="purple")
plt.title("Top netflix genres")
plt.xlabel("genres")
plt.ylabel("count")
plt.xticks(rotation=0)
plt.show()
directors=df["director"].str.split(",",expand=True).stack()
director_count=directors.value_counts().head(10)
print("\n top directors")
print(director_count)
plt.figure(figsize=(12,6))
director_count.plot(kind="bar",color="brown")
plt.title("Top netflix directors")
plt.xlabel("directors")
plt.ylabel("number of titles")
plt.xticks(rotation=0)
plt.show()