import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("sample superstore.csv")
print("first 5 rows")
print(df.head())
print("\ndataset info")
print(df.info())
total_sales=df["Sales"].sum()
print(total_sales)
top_products=df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False)
plt.figure(figsize=(10,5))
top_products.head(10).plot(kind="bar",color="blue")
plt.title("Top 10 products by month")
plt.xlabel("product")
plt.ylabel("sales")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
profit_data=df.groupby("Category")["Profit"].sum()
print("\nprofit by category")
print(profit_data)
plt.figure(figsize=(10,5))
profit_data.plot(kind="bar",color="red")
plt.title("profit by category")
plt.xlabel("category")
plt.ylabel("profit")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()