import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("spotify.csv")
print("\n first 5 rows")
print(df.head())
print("\n dataset shape")
print(df.shape)
print("\n columns")
print(df.columns)
print("\nmissing values")
print(df.isnull().sum())
df.columns=df.columns.str.strip()
df=df.drop_duplicates()
print("\n dataset shape after removing duplicate")
print(df.shape)
if "popularity" in df.columns:
    df["popularity"]=df["popularity"].fillna(df["popularity"].mean())
if "track_name" in df.columns and "popularity" in df.columns:
    top_songs=df[["track_name","popularity"]].sort_values(by="popularity",ascending=False).head(10)
    print("\n top 10 tracks \n")
    print(top_songs)
    plt.figure(figsize=(12,6))
    plt.bar(top_songs["track_name"],top_songs["popularity"])
    plt.xticks(rotation=75)
    plt.title("Top 10 song")
    plt.xlabel("song")
    plt.ylabel("popularity")
    plt.tight_layout()
    plt.show()
if "artist" in df.columns:
    top_artist=df["artist"].value_counts().head(10)
    print("\n top 10 artists \n")
    print(top_artist)
    plt.figure(figsize=(10,5))
    plt.bar(top_artist.index,top_artist.values)
    plt.xticks(rotation=75)
    plt.title("Top artists")
    plt.xlabel("artist")
    plt.ylabel("number of songs")
    plt.tight_layout()
    plt.show()
if "explicit" in df.columns:
    explicit_count=df['explicit'].value_counts()
    print("\n explicit vs non explicit songs")
    print(explicit_count)
    plt.figure(figsize=(6,6))
    plt.pie(explicit_count.values,
            labels=explicit_count.index,
            autopct="%1.1f%%")
    plt.title("explicit vs non explicit songs")
    plt.show()
if "danceability" in df.columns:
    print("\n average danceability")
    print(df["danceability"].mean())
    plt.figure(figsize=(8,5))
    plt.hist(df["danceability"],bins=20)
    plt.title("danceability distribution")
    plt.xlabel("danceability")
    plt.ylabel("number of songs")
    plt.show()
if "energy" in df.columns:
    print("\n average energy")
    print(df["energy"].mean())
    plt.figure(figsize=(8,5))
    plt.hist(df["energy"],bins=20)
    plt.title("energy distribution")
    plt.xlabel("energy")
    plt.ylabel("number of songs")
    plt.show()
numeric_columns=df.select_dtypes(include="number")
correlation=numeric_columns.corr()
print(correlation)
if "artist" in df.columns and "popularity" in df.columns:
    artist_popularity=df.groupby("artist")["popularity"].mean()
    artist_popularity=artist_popularity.sort_values(ascending=False).head(10)
    print("\n top artists by avg popularity")
    print(artist_popularity)
    plt.figure(figsize=(10,5))
    plt.bar(artist_popularity.index,artist_popularity.values)
    plt.xticks(rotation=75)
    plt.title("top artists by avg popularity")
    plt.xlabel("artist")
    plt.ylabel("avg popularity")
    plt.tight_layout()
    plt.show()
if "duration_ms" in df.columns:
    df["duration_ms"]=df["duration_ms"]/60000
    print("\n average song duration (min):")
    print(df["duration_ms"].mean())
    plt.figure(figsize=(8,5))
    plt.hist(df["duration_ms"],bins=20)
    plt.title("duration distribution")
    plt.xlabel("duration")
    plt.ylabel("number of songs")
    plt.show()





