import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("Telco-Customer-Churn.csv")
df.columns=df.columns.str.strip()
print("first 5 rows")
print(df.head())
print("\ndataset info")
print(df.info())
print("\nmissing values")
print(df.isnull().sum())
df["TotalCharges"]=pd.to_numeric(df["TotalCharges"],errors="coerce")
df["TotalCharges"].fillna(df["TotalCharges"].mean())
print("\nduplicate rows:",df.duplicated().sum())
print("\nchurn count")
print(df["Churn"].value_counts())
df["Churn"].value_counts().plot(kind="bar",color="blue")
plt.title("Churn vs non churn")
plt.xlabel("Churn")
plt.ylabel("count")
plt.show()
df["Churn"].value_counts().plot(kind="pie",autopct="%1.1f%%")
plt.title("Churn percentage")
plt.ylabel("")
plt.show()
plt.hist(df["tenure"],bins=20)
plt.title("customer tenure distribution")
plt.xlabel("tenure")
plt.ylabel("customer")
plt.show()
plt.hist(df["MonthlyCharges"],bins=20)
plt.title("monthly charges distribution")
plt.xlabel("months")
plt.ylabel("customer")
plt.show()
print("\naverage monthly charges")
print(df.groupby("Churn")["MonthlyCharges"].mean())
print("\ncontract type vs churn")
contract_churn=pd.crosstab(df["Contract"],df["Churn"])
print(contract_churn)
contract_churn.plot(kind="bar",color="black")
plt.title("Contract type vs churn")
plt.xlabel("Contract type")
plt.ylabel("customer")
plt.show()
df["Churn_Num"]=df["Churn"].map({"Yes":1,"No":0})
numeric_df=df.select_dtypes(include=["int64","float64"])
corr=numeric_df.corr()
plt.imshow(corr,cmap="coolwarm",aspect="auto")
plt.colorbar()
plt.xticks(range(len(corr.columns)),corr.columns,rotation=90)
plt.yticks(range(len(corr.columns)),corr.columns)
plt.title("Correlation")
plt.show()
print("\nFINAL INSIGHTS")
print("customers with high monthly charges are more likely to churn")
print("customers with short tenure leave more often")
print("monthly contract customer have highest churn rate")
print("long term customer are more loyal")
print("logistic regression can predict customer churn")