import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("trending_youtube_videos.csv")
print(df.head())
print(df.info())
df.columns=df.columns.str.strip()
df["publish_date"]=pd.to_datetime(df["publish_date"])
print("\nmissing values:")
print(df.isnull().sum())
df.drop_duplicates(inplace=True)
print("\n cleaned dataset shape")
print(df.shape)
total_views=df["views"].sum()
total_likes=df["likes"].sum()
total_comments=df["comment_count"].sum()
print("\ntotal views:",total_views)
print("\ntotal likes:",total_likes)
print("\ntotal comments:",total_comments)
top_categories=df.groupby("category")["views"].sum().sort_values(ascending=False).head(10)
print("\ntop categories:")
print(top_categories)
plt.figure(figsize=(10,5))
top_categories.plot(kind="bar",color="orange")
plt.title("Top categories by views")
plt.xlabel("Categories")
plt.ylabel("total views")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
top_channels=df.groupby("channel_title")["likes"].sum().sort_values(ascending=False).head(10)
print("\ntop channels:")
print(top_channels)
plt.figure(figsize=(10,5))
top_channels.plot(kind="bar",color="green")
plt.title("Top channels by likes")
plt.xlabel("Channels")
plt.ylabel("total likes")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
country_videos=df["country"].value_counts()
print("\n country-wise trending videos:")
print(country_videos)
plt.figure(figsize=(8,5))
country_videos.plot(kind="bar",color="brown")
plt.title("country-wise trending videos")
plt.xlabel("Country")
plt.ylabel("Number of videos")
plt.tight_layout()
plt.show()
df["month"]=df["publish_date"].dt.month_name()
monthly_trend=df["month"].value_counts()
print("\n monthly trending videos:")
print(monthly_trend)
plt.figure(figsize=(10,5))
monthly_trend.plot(kind="line",marker="o",color="black")
plt.title("monthly trending videos")
plt.xlabel("Month")
plt.ylabel("Number of videos")
plt.grid(True)
plt.tight_layout()
plt.show()
top_videos=df[["title","views"]].sort_values(by="views",ascending=False).head(10)
print("\ntop videos:")
print(top_videos)
df["engagement_rate"]=((df["likes"]+df["comment_count"])/df["views"])*100
top_engagement=df[["title","engagement_rate"]].sort_values(by="engagement_rate",ascending=False).head(10)
print("\ntop engagement:")
print(top_engagement)


